import {
  Grid2X2, Layers, Hexagon, Diamond, Circle, Triangle, Square, Cross, Star, Pentagon, Octagon, CircleDot, Box, Boxes, Blocks, Component as ComponentIcon,
  ChartNoAxesColumnIncreasing, ChartLine, ChartCandlestick, ChartArea, ChartPie, TrendingUp, TrendingDown, TrendingUpDown, Coins, DollarSign, Bitcoin, Wallet, Landmark, Scale, Gauge, Percent,
  Target, ArrowUpRight, ArrowDownRight, ArrowUpDown, ArrowLeftRight, Compass, Navigation, Route, Signpost, Repeat2, Shuffle, RotateCw, Move, Crosshair, FastForward, Anchor,
  Activity, Orbit, Atom, Dna, FlaskConical, Microscope, Telescope, Satellite, Radar, Cpu, CircuitBoard, Network, Workflow, GitBranch, Binary, Infinity as InfinityIcon,
  Mountain, Trees, Leaf, Sprout, Flower2, Sun, Moon, Eclipse, Cloud, Snowflake, Flame, Droplet, Waves, Wind, Zap, Feather,
  Shield, Crown, Trophy, Flag, Rocket, Gem, KeyRound, LockKeyhole, Eye, Lightbulb, Hourglass, Clock, Magnet, Puzzle, Fingerprint, Castle,
} from 'lucide-vue-next'
import type { SystemMeta } from '#systems/types'

/** Persist only stable keys; render the local line icon components. */
export const STRATEGY_ICONS = [
  { id: 'grid', label: 'Grid', category: 'Shapes', component: Grid2X2 },
  { id: 'layers', label: 'Layers', category: 'Shapes', component: Layers },
  { id: 'hexagon', label: 'Hexagon', category: 'Shapes', component: Hexagon },
  { id: 'diamond', label: 'Diamond', category: 'Shapes', component: Diamond },
  { id: 'circle', label: 'Circle', category: 'Shapes', component: Circle },
  { id: 'triangle', label: 'Triangle', category: 'Shapes', component: Triangle },
  { id: 'square', label: 'Square', category: 'Shapes', component: Square },
  { id: 'cross', label: 'Cross', category: 'Shapes', component: Cross },
  { id: 'star', label: 'Star', category: 'Shapes', component: Star },
  { id: 'pentagon', label: 'Pentagon', category: 'Shapes', component: Pentagon },
  { id: 'octagon', label: 'Octagon', category: 'Shapes', component: Octagon },
  { id: 'circle-dot', label: 'Circle dot', category: 'Shapes', component: CircleDot },
  { id: 'box', label: 'Box', category: 'Shapes', component: Box },
  { id: 'boxes', label: 'Boxes', category: 'Shapes', component: Boxes },
  { id: 'blocks', label: 'Blocks', category: 'Shapes', component: Blocks },
  { id: 'component', label: 'Components', category: 'Shapes', component: ComponentIcon },
  { id: 'bars', label: 'Bars', category: 'Charts & finance', component: ChartNoAxesColumnIncreasing },
  { id: 'chart-line', label: 'Line chart', category: 'Charts & finance', component: ChartLine },
  { id: 'candlesticks', label: 'Candlesticks', category: 'Charts & finance', component: ChartCandlestick },
  { id: 'chart-area', label: 'Area chart', category: 'Charts & finance', component: ChartArea },
  { id: 'chart-pie', label: 'Pie chart', category: 'Charts & finance', component: ChartPie },
  { id: 'trending-up', label: 'Trending up', category: 'Charts & finance', component: TrendingUp },
  { id: 'trending-down', label: 'Trending down', category: 'Charts & finance', component: TrendingDown },
  { id: 'trend-change', label: 'Trend change', category: 'Charts & finance', component: TrendingUpDown },
  { id: 'coins', label: 'Coins', category: 'Charts & finance', component: Coins },
  { id: 'dollar', label: 'Dollar', category: 'Charts & finance', component: DollarSign },
  { id: 'bitcoin', label: 'Bitcoin', category: 'Charts & finance', component: Bitcoin },
  { id: 'wallet', label: 'Wallet', category: 'Charts & finance', component: Wallet },
  { id: 'landmark', label: 'Bank', category: 'Charts & finance', component: Landmark },
  { id: 'scale', label: 'Balance', category: 'Charts & finance', component: Scale },
  { id: 'gauge', label: 'Gauge', category: 'Charts & finance', component: Gauge },
  { id: 'percent', label: 'Percent', category: 'Charts & finance', component: Percent },
  { id: 'target', label: 'Target', category: 'Direction', component: Target },
  { id: 'arrow-up-right', label: 'Arrow up right', category: 'Direction', component: ArrowUpRight },
  { id: 'arrow-down-right', label: 'Arrow down right', category: 'Direction', component: ArrowDownRight },
  { id: 'arrows-up-down', label: 'Arrows up down', category: 'Direction', component: ArrowUpDown },
  { id: 'arrows-left-right', label: 'Arrows left right', category: 'Direction', component: ArrowLeftRight },
  { id: 'compass', label: 'Compass', category: 'Direction', component: Compass },
  { id: 'navigation', label: 'Navigation', category: 'Direction', component: Navigation },
  { id: 'route', label: 'Route', category: 'Direction', component: Route },
  { id: 'signpost', label: 'Signpost', category: 'Direction', component: Signpost },
  { id: 'repeat', label: 'Repeat', category: 'Direction', component: Repeat2 },
  { id: 'shuffle', label: 'Shuffle', category: 'Direction', component: Shuffle },
  { id: 'rotate', label: 'Rotate', category: 'Direction', component: RotateCw },
  { id: 'move', label: 'Move', category: 'Direction', component: Move },
  { id: 'crosshair', label: 'Crosshair', category: 'Direction', component: Crosshair },
  { id: 'fast-forward', label: 'Fast forward', category: 'Direction', component: FastForward },
  { id: 'anchor', label: 'Anchor', category: 'Direction', component: Anchor },
  { id: 'wave', label: 'Wave', category: 'Science & technology', component: Activity },
  { id: 'orbit', label: 'Orbit', category: 'Science & technology', component: Orbit },
  { id: 'atom', label: 'Atom', category: 'Science & technology', component: Atom },
  { id: 'dna', label: 'DNA', category: 'Science & technology', component: Dna },
  { id: 'flask', label: 'Flask', category: 'Science & technology', component: FlaskConical },
  { id: 'microscope', label: 'Microscope', category: 'Science & technology', component: Microscope },
  { id: 'telescope', label: 'Telescope', category: 'Science & technology', component: Telescope },
  { id: 'satellite', label: 'Satellite', category: 'Science & technology', component: Satellite },
  { id: 'radar', label: 'Radar', category: 'Science & technology', component: Radar },
  { id: 'cpu', label: 'Processor', category: 'Science & technology', component: Cpu },
  { id: 'circuit', label: 'Circuit', category: 'Science & technology', component: CircuitBoard },
  { id: 'network', label: 'Network', category: 'Science & technology', component: Network },
  { id: 'workflow', label: 'Workflow', category: 'Science & technology', component: Workflow },
  { id: 'git-branch', label: 'Branches', category: 'Science & technology', component: GitBranch },
  { id: 'binary', label: 'Binary', category: 'Science & technology', component: Binary },
  { id: 'infinity', label: 'Infinity', category: 'Science & technology', component: InfinityIcon },
  { id: 'mountain', label: 'Mountain', category: 'Nature', component: Mountain },
  { id: 'trees', label: 'Trees', category: 'Nature', component: Trees },
  { id: 'leaf', label: 'Leaf', category: 'Nature', component: Leaf },
  { id: 'sprout', label: 'Sprout', category: 'Nature', component: Sprout },
  { id: 'flower', label: 'Flower', category: 'Nature', component: Flower2 },
  { id: 'sun', label: 'Sun', category: 'Nature', component: Sun },
  { id: 'moon', label: 'Moon', category: 'Nature', component: Moon },
  { id: 'eclipse', label: 'Eclipse', category: 'Nature', component: Eclipse },
  { id: 'cloud', label: 'Cloud', category: 'Nature', component: Cloud },
  { id: 'snowflake', label: 'Snowflake', category: 'Nature', component: Snowflake },
  { id: 'flame', label: 'Flame', category: 'Nature', component: Flame },
  { id: 'droplet', label: 'Droplet', category: 'Nature', component: Droplet },
  { id: 'waves', label: 'Waves', category: 'Nature', component: Waves },
  { id: 'wind', label: 'Wind', category: 'Nature', component: Wind },
  { id: 'bolt', label: 'Lightning', category: 'Nature', component: Zap },
  { id: 'feather', label: 'Feather', category: 'Nature', component: Feather },
  { id: 'shield', label: 'Shield', category: 'Objects', component: Shield },
  { id: 'crown', label: 'Crown', category: 'Objects', component: Crown },
  { id: 'trophy', label: 'Trophy', category: 'Objects', component: Trophy },
  { id: 'flag', label: 'Flag', category: 'Objects', component: Flag },
  { id: 'rocket', label: 'Rocket', category: 'Objects', component: Rocket },
  { id: 'gem', label: 'Gem', category: 'Objects', component: Gem },
  { id: 'key', label: 'Key', category: 'Objects', component: KeyRound },
  { id: 'lock', label: 'Lock', category: 'Objects', component: LockKeyhole },
  { id: 'eye', label: 'Eye', category: 'Objects', component: Eye },
  { id: 'lightbulb', label: 'Lightbulb', category: 'Objects', component: Lightbulb },
  { id: 'hourglass', label: 'Hourglass', category: 'Objects', component: Hourglass },
  { id: 'clock', label: 'Clock', category: 'Objects', component: Clock },
  { id: 'magnet', label: 'Magnet', category: 'Objects', component: Magnet },
  { id: 'puzzle', label: 'Puzzle', category: 'Objects', component: Puzzle },
  { id: 'fingerprint', label: 'Fingerprint', category: 'Objects', component: Fingerprint },
  { id: 'castle', label: 'Castle', category: 'Objects', component: Castle },
] as const

export const STRATEGY_ICON_GROUPS = [...new Set(STRATEGY_ICONS.map(icon => icon.category))]

export function strategyIcon(system?: Pick<SystemMeta, 'id' | 'icon'>) {
  const fallback = system?.id === 'lces' ? 'layers' : system?.id === 'sces' ? 'hexagon' : 'grid'
  return STRATEGY_ICONS.find(icon => icon.id === (system?.icon || fallback)) ?? STRATEGY_ICONS[0]
}
