//! The MCP bridge (ARCHITECTURE.md §7).
//!
//! Every module declares `capabilities` in its `module.json`. The validator
//! flattens them into `modules/registry.generated.json`, and this crate turns
//! that into the tool catalogue an agent sees, named
//! `quantsuite.<module>.<name>`.
//!
//! This crate owns the *policy* — what an agent is allowed to call, and under
//! what approval — not the transport. It is deliberately free of Tauri and of
//! QuantMCP internals so the policy can be tested on its own.
//!
//! ## Where the rest of the path lives
//!
//! The transport is QuantMCP's: `modules/mcp/crate/src/mcp_server.rs` serves
//! this catalogue in its `tools/list` response and dispatches every
//! `quantsuite.*` `tools/call` through `qs_core::agent::request`. That broker
//! (`crates/qs-core/src/agent.rs`) applies [`decide_tool`] under the user's
//! approval mode, queues anything that needs confirmation, and lets the shell
//! perform the actual `invoke`. So an external agent *does* reach these tools —
//! never around the gate below, always through it.

use serde::{Deserialize, Serialize};
use std::{collections::HashSet, sync::OnceLock};

/// Generated by `scripts/validate-modules.mjs` from every `module.json`.
const REGISTRY_JSON: &str = include_str!("../../../modules/registry.generated.json");

/// How much damage a capability can do. Drives [`decide`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SideEffects {
    /// No state change.
    Read,
    /// Expensive, but nothing leaves the machine.
    Compute,
    /// Changes local state.
    Write,
    /// Network calls, orders, deploys. Never auto-approved.
    External,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ApprovalMode {
    /// Every write is confirmed by the user. The default, deliberately.
    #[default]
    Strict,
    /// Writes go through; `external` still does not.
    Relaxed,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(tag = "decision", rename_all = "snake_case")]
pub enum Decision {
    /// Dispatch immediately.
    Allow,
    /// Ask the user first; the reason is shown in the prompt.
    Prompt { reason: String },
    /// Refuse outright.
    Deny { reason: String },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Capability {
    /// `quantsuite.<module>.<name>`
    pub tool: String,
    pub module: String,
    pub name: String,
    /// `plugin:<module>|<command>`
    pub command: String,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "sideEffects")]
    pub side_effects: SideEffects,
    /// Optional JSON Schema for the tool's arguments, straight from the
    /// module manifest. `None` means the transport serves a permissive
    /// schema and the description carries the whole contract.
    #[serde(rename = "inputSchema", default)]
    pub input_schema: Option<serde_json::Value>,
}

#[derive(Deserialize)]
struct Registry {
    #[serde(default)]
    capabilities: Vec<Capability>,
    apps: Vec<SuiteApp>,
}

#[derive(Deserialize)]
struct SuiteApp {
    id: String,
    modules: Vec<String>,
    #[serde(rename = "defaultEnabled")]
    default_enabled: bool,
}

pub const APP_ENABLED_PREFIX: &str = "apps.enabled.";

fn apps() -> &'static [SuiteApp] {
    static APPS: OnceLock<Vec<SuiteApp>> = OnceLock::new();
    APPS.get_or_init(|| serde_json::from_str::<Registry>(REGISTRY_JSON).expect("valid module registry").apps)
}

/// The same ownership as the UI, including the old routes/plugin namespaces
/// now contained by QuantFlow and QuantAlgo.
pub fn app_for_module(module: &str) -> Option<&'static str> {
    let module = match module {
        "plan" | "habit" => "flow",
        "systems" => "algo",
        other => other,
    };
    apps().iter().find(|app| app.modules.iter().any(|id| id == module)).map(|app| app.id.as_str())
}

pub fn validate_app_setting(key: &str, value: &serde_json::Value) -> Result<(), String> {
    if let Some(id) = key.strip_prefix(APP_ENABLED_PREFIX) {
        if id == "dashboard" || !apps().iter().any(|app| app.id == id) {
            return Err(format!("Unknown or non-configurable app '{id}'"));
        }
        if !value.is_boolean() {
            return Err("App activation must be a boolean".into());
        }
    }
    Ok(())
}

/// Saved switches override the manifest defaults shared with the shell.
pub struct AppAvailability {
    disabled: HashSet<String>,
}

impl Default for AppAvailability {
    fn default() -> Self {
        Self::from_settings(&serde_json::Map::new())
    }
}

impl AppAvailability {
    pub fn from_settings(settings: &serde_json::Map<String, serde_json::Value>) -> Self {
        Self {
            disabled: apps().iter().filter(|app| {
                app.id != "dashboard" && !settings.get(&format!("{APP_ENABLED_PREFIX}{}", app.id))
                    .and_then(serde_json::Value::as_bool).unwrap_or(app.default_enabled)
            }).map(|app| app.id.clone()).collect(),
        }
    }

    pub fn module_enabled(&self, module: &str) -> bool {
        app_for_module(module).map_or(true, |id| !self.disabled.contains(id))
    }

    /// Built-in and custom MCP tools belong to QuantMCP. Namespaced suite
    /// capabilities follow their owning module, independently of QuantMCP UI.
    pub fn tool_enabled(&self, tool: &str) -> bool {
        let module = tool.strip_prefix("quantsuite.").and_then(|rest| rest.split('.').next()).unwrap_or("mcp");
        self.module_enabled(module)
    }
}

/// The full tool catalogue, in manifest order. The registry is embedded at
/// compile time, so it is parsed once and borrowed from there on — every agent
/// call goes through [`decide_tool`] and [`find`].
pub fn capabilities() -> &'static [Capability] {
    static CATALOGUE: OnceLock<Vec<Capability>> = OnceLock::new();
    CATALOGUE.get_or_init(|| {
        serde_json::from_str::<Registry>(REGISTRY_JSON)
            .map(|r| r.capabilities)
            .unwrap_or_default()
    })
}

pub fn find(tool: &str) -> Option<&'static Capability> {
    capabilities().iter().find(|c| c.tool == tool)
}

/// The gate.
///
/// `external` is never auto-approved regardless of mode — that covers exchange
/// orders and bot deployment, where "the agent seemed confident" is not a
/// sufficient reason to move money.
pub fn decide(cap: &Capability, mode: ApprovalMode) -> Decision {
    match cap.side_effects {
        SideEffects::Read | SideEffects::Compute => Decision::Allow,
        SideEffects::Write => match mode {
            ApprovalMode::Relaxed => Decision::Allow,
            ApprovalMode::Strict => Decision::Prompt {
                reason: format!("{} changes local state", cap.tool),
            },
        },
        SideEffects::External => Decision::Prompt {
            reason: format!(
                "{} has effects outside this machine and is never auto-approved",
                cap.tool
            ),
        },
    }
}

/// Decide for a tool name, rejecting anything not in the catalogue.
pub fn decide_tool(tool: &str, mode: ApprovalMode) -> Decision {
    match find(tool) {
        Some(cap) => decide(cap, mode),
        None => Decision::Deny {
            reason: format!("unknown tool '{tool}'"),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn app_switches_filter_whole_groups_and_legacy_namespaces() {
        let settings = serde_json::json!({
            "apps.enabled.quantzen": false,
            "apps.enabled.quantview": false,
            "apps.enabled.dashboard": false,
        });
        let availability = AppAvailability::from_settings(settings.as_object().unwrap());
        for module in ["notes", "flow", "plan", "habit", "finance", "terminal", "script", "systems", "algo"] {
            assert!(!availability.module_enabled(module), "{module}");
            assert!(!availability.tool_enabled(&format!("quantsuite.{module}.test")), "{module}");
        }
        for module in ["mcp", "memory", "pilot", "code", "canvas", "console", "hud", "core"] {
            assert!(availability.module_enabled(module), "{module}");
        }
        assert!(availability.tool_enabled("search_code"));
        assert!(availability.tool_enabled("custom_script"));
        for cap in capabilities() {
            let expected = !matches!(app_for_module(&cap.module), Some("quantzen" | "quantview"));
            assert_eq!(availability.tool_enabled(&cap.tool), expected, "{}", cap.tool);
        }
    }

    #[test]
    fn every_app_can_be_disabled_and_reenabled_without_affecting_others() {
        let mut settings: serde_json::Map<String, serde_json::Value> = apps().iter()
            .map(|app| (format!("{APP_ENABLED_PREFIX}{}", app.id), serde_json::Value::Bool(true))).collect();
        for app in apps().iter().filter(|app| app.id != "dashboard") {
            let key = format!("{APP_ENABLED_PREFIX}{}", app.id);
            settings.insert(key.clone(), serde_json::Value::Bool(false));
            let disabled = AppAvailability::from_settings(&settings);
            for cap in capabilities() {
                assert_eq!(disabled.tool_enabled(&cap.tool), app_for_module(&cap.module) != Some(app.id.as_str()), "{} / {}", app.id, cap.tool);
            }
            assert_eq!(disabled.tool_enabled("search_code"), app.id != "quantagent");
            assert_eq!(disabled.tool_enabled("custom_script"), app.id != "quantagent");
            settings.insert(key, serde_json::Value::Bool(true));
            let restored = AppAvailability::from_settings(&settings);
            assert!(capabilities().iter().all(|cap| restored.tool_enabled(&cap.tool)));
        }
    }

    #[test]
    fn fresh_settings_enable_all_app_tools_and_saved_switches_override_defaults() {
        let fresh = AppAvailability::default();
        let mut settings = serde_json::json!({
            "apps.enabled.quantzen": true,
            "apps.enabled.quantview": true,
        });
        let enabled = AppAvailability::from_settings(settings.as_object().unwrap());
        for cap in capabilities() {
            assert!(fresh.tool_enabled(&cap.tool), "{}", cap.tool);
            assert!(enabled.tool_enabled(&cap.tool), "{}", cap.tool);
        }
        assert!(fresh.tool_enabled("search_code"));
        settings["apps.enabled.quantzen"] = serde_json::Value::Bool(false);
        let reloaded: serde_json::Map<String, serde_json::Value> = serde_json::from_str(&settings.to_string()).unwrap();
        let restored = AppAvailability::from_settings(&reloaded);
        assert!(!restored.tool_enabled("quantsuite.notes.search"));
        assert!(restored.tool_enabled("quantsuite.algo.list_strategies"));
    }

    #[test]
    fn app_settings_reject_invalid_writes_and_keep_home_available() {
        use serde_json::json;
        assert!(validate_app_setting("apps.enabled.quantzen", &json!(false)).is_ok());
        assert!(validate_app_setting("apps.enabled.quantzen", &json!("false")).is_err());
        assert!(validate_app_setting("apps.enabled.dashboard", &json!(false)).is_err());
        assert!(validate_app_setting("apps.enabled.unknown", &json!(false)).is_err());
        assert!(validate_app_setting("unrelated", &json!({})).is_ok());
    }

    #[test]
    fn registry_parses_and_is_not_empty() {
        let caps = capabilities();
        assert!(!caps.is_empty(), "generated registry has no capabilities");
        for c in caps {
            assert!(
                c.tool == format!("quantsuite.{}.{}", c.module, c.name),
                "tool name not canonical: {}",
                c.tool
            );
            let plugin = c.command.strip_prefix("plugin:").and_then(|command| command.split('|').next()).unwrap_or("");
            // Composite modules retain their underlying plugins.
            assert!(
                plugin == c.module
                    || (c.module == "flow" && matches!(plugin, "plan" | "habit"))
                    || (c.module == "algo" && plugin == "systems"),
                "capability {} dispatches outside its own module: {}",
                c.tool,
                c.command
            );
        }
    }

    #[test]
    fn reads_and_computes_are_auto_approved() {
        for mode in [ApprovalMode::Strict, ApprovalMode::Relaxed] {
            for c in capabilities()
                .iter()
                .filter(|c| matches!(c.side_effects, SideEffects::Read | SideEffects::Compute))
            {
                assert_eq!(decide(c, mode), Decision::Allow, "{}", c.tool);
            }
        }
    }

    #[test]
    fn external_is_never_auto_approved() {
        for mode in [ApprovalMode::Strict, ApprovalMode::Relaxed] {
            for c in capabilities()
                .iter()
                .filter(|c| c.side_effects == SideEffects::External)
            {
                assert!(
                    matches!(decide(c, mode), Decision::Prompt { .. }),
                    "{} was auto-approved in {:?} mode",
                    c.tool,
                    mode
                );
            }
        }
    }

    #[test]
    fn starting_the_bot_is_classified_external() {
        let cap = find("quantsuite.algo.start_bot").expect("start_bot capability missing");
        assert_eq!(cap.side_effects, SideEffects::External);
    }

    #[test]
    fn unknown_tools_are_denied() {
        assert!(matches!(
            decide_tool("quantsuite.algo.drain_wallet", ApprovalMode::Relaxed),
            Decision::Deny { .. }
        ));
    }
}
