"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the hud module."
permissions = [
  "allow-capture-screen",
  "allow-get-cursor-position",
  "allow-get-available-monitors",
  "allow-load-config",
  "allow-save-config",
  "allow-tuck-window",
  "allow-show-window",
  "allow-is-window-tucked",
  "allow-setup-window-size",
  "allow-set-window-position",
  "allow-open-region-selector",
  "allow-set-selected-region",
  "allow-get-selected-region",
  "allow-pick-screen-color",
  "allow-pick-folder",
  "allow-pick-file",
  "allow-launch-app",
  "allow-get-app-icon",
  "allow-get-default-screenshots-folder",
  "allow-list-os-screenshots",
  "allow-read-screenshot-file",
  "allow-read-screenshot-thumbnail",
  "allow-open-screenshots-folder",
  "allow-copy-screenshot-to-clipboard",
  "allow-open-color-picker-overlay",
  "allow-set-picked-color",
  "allow-get-picked-color",
  "allow-open-screenshot-preview",
  "allow-get-screenshot-preview-path",
  "allow-close-screenshot-preview",
  "allow-create-dual-window",
  "allow-close-dual-window",
  "allow-show-notification-popup",
  "allow-speech-status",
  "allow-speech-setup",
  "allow-speech-start",
  "allow-speech-stop",
  "allow-speech-cancel",
  "allow-speech-devices",
  "allow-speech-apply-settings",
  "allow-speech-engine-start",
  "allow-speech-engine-stop",
  "allow-speech-engine-logs",
  "allow-analyze-chart",
  "allow-save-temp-image",
  "allow-open-hud",
  "allow-close-hud",
]
